services:
  - type: web
    name: nifty-tracker
    env: docker
    plan: free
    autoDeploy: false
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: HEADLESS
        value: "true"
